version: 0.0
os: linux
files:
  - source: /{{WAR_FILE_NAME}}
    destination: /tmp/
 
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: application_start.sh
      timeout: 300
      runas: root