version: 0.2

# env:
#   variables:
#     DO_STATIC_SCAN: "$doStaticScan"  # Using the variable passed from CodePipeline

phases:
  install:
    commands:
      - echo "Install phase started"

  pre_build:
    commands:
      - echo "Pre-build phase started"
  
  build:
    commands:
      - echo ${doDASTScan}
      - echo "${doDASTScan}"
      - |
        # Convert environment variable to lowercase for comparison
        if [ "$(echo $doDASTScan | tr '[:upper:]' '[:lower:]')" = "yes" ]; then
          echo "automation for DAST Phase"
        else
          echo "Skipping DAST and proceeding with Deploy"
        fi
 
#   post_build:
#     commands:
#       - echo "SAST/SCA phases completed"
#       - echo "Post-build phase started"
#       - cp target/hello-world-1.0.2.war .
#       - mv hello-world-1.0.2.war hello-world.war
#       - mkdir build_artifacts
#       - cp hello-world.war buildspec-lab.yml buildspec-pp.yml appspec.yml application_start.sh build_artifacts/
 
# artifacts:
#   files:
#     - '**/build_artifacts/*'
#   discard-paths: yes
